### ISSUE TITLE
Release_8.0: Whoops when accessing a testoverview, when course is allocated in "Group/Course Filter"

### ISSUE THREAD

**Issue by samuelinniger** [DatabayAG/TestOverview#9]
(Only) if a course is allocated in the Group/Courses filter...

<img width="1171" alt="grafik" src="https://github.com/user-attachments/assets/1a380df8-1a55-40b4-9644-5a4bc31ed5e0">

I later am not able to access the Testoverview-Object: --> Whoops 
E.g. when clicking...
a) on a direct link,
b) or clicking on the object in the course,
c) or just clicking on the tab "Content"...

Click on Tab "Content" 
<img width="331" alt="grafik" src="https://github.com/user-attachments/assets/334dc6dc-0764-48de-8b9b-c528fc907b8c">

leads to:
 Whoops \ Exception \ ErrorException (E_WARNING)
Undefined property: stdClass::$type

<img width="1277" alt="grafik" src="https://github.com/user-attachments/assets/fef2aecf-a2a7-437e-b901-3d7126a61deb">

Plugin Version 8.0.0.
ILIAS v8.14 2024-08-13

**Comment by mbecker-databay** [comment]
Fix in git

**Comment by samuelinniger** [comment]
I still get a crash, now with a different error message:
<img width="1279" alt="grafik" src="https://github.com/user-attachments/assets/bceacb65-41af-4f2e-86d2-dcfeb267645f">

**Comment by Rillke** [comment]
@samuelinniger Did you find any workaround? The function `getTestResult()` does a lot of things ...

Frauke reported the second issue [to Mantis](https://mantis.ilias.de/view.php?id=43717) because it's an ILIAS core function.

**Comment by samuelinniger** [comment]
@Rillke No, unfortunately not (we're currently not using the plugin, just evaluating it).
@mjansenDatabay @mbecker-databay 
Could you please reopen this issue and take a look at it. Thanks!

**Comment by Rillke** [comment]
I added some debugging output:

```
[12caa] [2025-01-20 19:34:34.781500] unihalle_root.WARNING: ilTable2GUI::getHTML:158 obj id 584559  
[12caa] [2025-01-20 19:34:34.781728] unihalle_root.WARNING: ilTestOverviewTableGUI::fillRow:1362 active id: 0  
[12caa] [2025-01-20 19:34:34.783600] unihalle_root.WARNING: ilTestOverviewTableGUI::fillRow:1362 $sequence is  
[12caa] [2025-01-20 19:34:34.783675] unihalle_root.WARNING: ilTestOverviewTableGUI::fillRow:1362 [false,false,false,false,false,false,false,false]  
[12caa] [2025-01-20 19:34:34.783958] unihalle_root.WARNING: ilTestOverviewTableGUI::fillRow:1362 QUIDs  
[12caa] [2025-01-20 19:34:34.784023] unihalle_root.WARNING: ilTestOverviewTableGUI::fillRow:1362 "qpl_questions.question_id IN (0,0,0,0,0,0,0,0)"  
[12caa] [2025-01-20 19:34:34.784126] unihalle_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 2 Undefined array key 0 in /var/www/ilias/Modules/Test/classes/class.ilObjTest.php:3420#0 /var/www/ilias/Services/Init/classes/class.ilErrorHandling.php(459): Whoops\Run->handleError(2, 'Undefined array...', '/var/www/ilias/...', 3420)
#1 /var/www/ilias/Modules/Test/classes/class.ilObjTest.php(3420): ilErrorHandling->handlePreWhoops(2, 'Undefined array...', '/var/www/ilias/...', 3420)
#2 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/TestOverview/classes/GUI/class.ilTestOverviewTableGUI.php(263): ilObjTest->getTestResult(0)
#3 /var/www/ilias/Services/Table/classes/class.ilTable2GUI.php(1362): ilTestOverviewTableGUI->fillRow(Array)
#4 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/TestOverview/classes/class.ilObjTestOverviewGUI.php(158): ilTable2GUI->getHTML()
#5 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/TestOverview/classes/class.ilObjTestOverviewGUI.php(114): ilObjTestOverviewGUI->showContent()
#6 /var/www/ilias/Services/Repository/PluginSlot/class.ilObjectPluginGUI.php(174): ilObjTestOverviewGUI->performCommand('showContent')
#7 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(203): ilObjectPluginGUI->executeCommand()
#8 /var/www/ilias/Services/Repository/PluginSlot/class.ilObjPluginDispatchGUI.php(61): ilCtrl->forwardCommand(Object(ilObjTestOverviewGUI))
#9 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(203): ilObjPluginDispatchGUI->executeCommand()
#10 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(178): ilCtrl->forwardCommand(Object(ilObjPluginDispatchGUI))
#11 /var/www/ilias/ilias.php(24): ilCtrl->callBaseClass()
#12 {main}  
```

**Comment by Rillke** [comment]
As a workaround, I will probably add 

```php
            if ($activeId === 0) {
                $result = $this->lng->txt("rep_robj_xtov_overview_test_not_passed");
                $results[]  = 0 . "##no-result##";
                $this->populateNoLinkCell(
                    $result,
                    $this->getCSSByTestResult(null)
                );
                $this->tpl->setCurrentBlock('cell');
                $this->tpl->parseCurrentBlock();
                continue;
            }
```

to https://github.com/DatabayAG/TestOverview/blob/Release_8.0/classes/GUI/class.ilTestOverviewTableGUI.php#L256

According to our database, it crashes if this plugin attempts to get the result for a user who didn't take the test.

**Comment by mbecker-databay** [comment]
@Rillke In general, funding would of course be great, but not for this particular issue here.
I will have a look at this now asap.

**Comment by mbecker-databay** [comment]
I cannot reproduce this, I think there is an underlying cause in the databases in addition to the participant without pass. 
But: I do not doubt this report: There are related other issues open in the core. (You will find them if you search for "getTestResults" on mantis, there are plenty)
I would leave this for fixing in the core and close here.
